tests: Resolve compilation error linked to Catch2
Compilation of IGA-ADS with Catch2 v3 terminates with several errors:

iga-ads/tests/main.cpp:5:10: fatal error: catch2/catch.hpp: No such file
or directory
    5 | #include <catch2/catch.hpp>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.

Error vanishes when compiling with Catch2 v2.x branch because v3 renamed
catch2/catch.hpp to catch2/catch_all.hpp. Upgrade IGA-ADS to support v3
in order to resolve this error. In tests/, replace every occurence of
catch2/catch.hpp with catch2/catch_all.hpp and Approx with
Catch::Approx, remove main.cpp and link against Catch::Catch2WithMain
instead of Catch::Catch2. Change default version of Catch2 into
v3.3.2. Tested on Fedora 36.

Signed-off-by: Michał Grzelak <mchl.grzlk@gmail.com>